Blog/Areas/Admin/Controllers/ArticulosController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Blog.AccesoDatos.Data.Repository;
using Blog.Modelos.ViewModels;
using Blog.Modelos;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Blog.Modelos.Utilidades;

namespace Blog.Areas.Admin
{
    [Authorize(Roles = Constantes.admin)]

    [Area("Admin")]
    public class ArticulosController : Controller
    {
        private readonly IContenedorTrabajo _contenedorTrabajo;
        private readonly IWebHostEnvironment _host;


        public ArticulosController(IContenedorTrabajo container, IWebHostEnvironment webHost )
        {
            this._contenedorTrabajo = container;
            _host = webHost;
        }
        public IActionResult Index()
        {
          
           
            return View();


        }
        [HttpGet]
        public IActionResult Create()
        {

            ArticuloVM avm = new ArticuloVM()
            {
                Articulo = new Modelos.Articulo(),
                Categorias = this._contenedorTrabajo.UTCategoria.GetListaCategorias()


            };
            return View(avm);


        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {

         ArticuloVM  avm = new ArticuloVM()
            {
                Articulo = new Modelos.Articulo(),
                Categorias = this._contenedorTrabajo.UTCategoria.GetListaCategorias()


            };
            if(id != null)
            {

                avm.Articulo = this._contenedorTrabajo.UTArticulo.Get(id.GetValueOrDefault());
                return View(avm);

            }
            else
            {
                return NotFound("Contenido no encontrado");
            }

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ArticuloVM avm)
        {
            if(ModelState.IsValid)
            {

                string rutaPrincipal = _host.WebRootPath;
                var archivos = HttpContext.Request.Form.Files;
                if (avm.Articulo.Id == 0)
                {
                    string nombreArchivo = Guid.NewGuid().ToString();
                    var subidas = Path.Combine(rutaPrincipal, @"articulosImagenes");
                    var extension = Path.GetExtension(archivos[0].FileName);
                    using (var fileStrean = new FileStream(Path.Combine(subidas, nombreArchivo + extension), FileMode.Create))
                    {
                        archivos[0].CopyTo(fileStrean);
                    }
                    avm.Articulo.UrlImagen = @"\articulosImagenes\" + nombreArchivo + extension;
                    avm.Articulo.FechaCreacion = DateTime.Now.ToString();
                    _contenedorTrabajo.UTArticulo.Add(avm.Articulo);
                    _contenedorTrabajo.Save();
                   return  RedirectToAction(nameof(Index));


                }
                
            }


            return View(avm);

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(ArticuloVM avm)
        {
            if (ModelState.IsValid)
            {

                string rutaPrincipal = _host.WebRootPath;
                var archivos = HttpContext.Request.Form.Files;
                var articulo = _contenedorTrabajo.UTArticulo.Get(avm.Articulo.Id);
                if (archivos.Count() > 0)
                {

                    // editamos archivo
                    string nombreArchivo = Guid.NewGuid().ToString();
                    var subidas = Path.Combine(rutaPrincipal, @"articulosImagenes");
                    var extension = Path.GetExtension(archivos[0].FileName);
                    using (var fileStrean = new FileStream(Path.Combine(subidas, nombreArchivo + extension), FileMode.Create))
                    {
                        archivos[0].CopyTo(fileStrean);
                    }
                    avm.Articulo.UrlImagen = @"\articulosImagenes\" + nombreArchivo + extension;
               


                }
                else
                {
                    avm.Articulo.UrlImagen = articulo.UrlImagen;

                }
                avm.Articulo.FechaCreacion = DateTime.Now.ToString();

                _contenedorTrabajo.UTArticulo.Update(avm.Articulo);
                _contenedorTrabajo.Save();
                return RedirectToAction(nameof(Index));

            }


            return View(avm);

        }

        /// <summary>
        /// ////////////////apiii
        /// </summary>
        /// <returns></returns>
        #region AJAXAPI
        [HttpGet]
        public IActionResult GetAll()
        {

            return Json(new { data = this._contenedorTrabajo.UTArticulo.GetAll(includeProperties: "Categoria") });

        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            Articulo art = this._contenedorTrabajo.UTArticulo.Get(id);
            if (art == null)
            {

                return Json(new { success = false, message = "Error borrando el articulo" });
            }
            else
            {
                this._contenedorTrabajo.UTArticulo.Remove(art);
                _contenedorTrabajo.Save();
                return Json(new { success = true, message = "Articulo borrado!" });

            }


        }


        #endregion
    }
}

Blog/Areas/Admin/Controllers/CategoriasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Blog.AccesoDatos.Data.Repository;
using Blog.Modelos;
using Blog.Modelos.Utilidades;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Blog.Areas.Admin.Controllers
{
    [Authorize(Roles = Constantes.admin)]

    [Area("Admin")]
    public class CategoriasController : Controller
    {

        private readonly IContenedorTrabajo _contenedorTrabajo;

        
        public CategoriasController(IContenedorTrabajo contenedor)
        {
            _contenedorTrabajo = contenedor;
        }
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }


        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        #region
        //llamas a la api
        [HttpGet]
        public IActionResult GetAll()
        {
            return Json( new { data = this._contenedorTrabajo.UTCategoria.GetAll() });
        }
        [HttpGet]
        public IActionResult Edit(int id)
        {
            Categoria c = _contenedorTrabajo.UTCategoria.Get(id);
            if (c != null)
            {
                return View(c);
            }
            return NotFound();
        }
        [HttpPost]
        public IActionResult Create(Categoria cat)
        {
            if(ModelState.IsValid)
            {
                this._contenedorTrabajo.UTCategoria.Add(cat);
                this._contenedorTrabajo.Save();
                return (RedirectToAction(nameof(Index)));

            }
            return View(cat);

        }

        [HttpPost]
        public IActionResult Edit(Categoria cat)
        {
            if (ModelState.IsValid)
            {
                this._contenedorTrabajo.UTCategoria.Update(cat);
                this._contenedorTrabajo.Save();
                return (RedirectToAction(nameof(Index)));

            }
            return View(cat);

        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
           Categoria cat = _contenedorTrabajo.UTCategoria.Get(id);
            if (cat == null)
            {

                return Json(new { success = false,message = "Error borrando la categoria" });
            }
            else
            {
                _contenedorTrabajo.UTCategoria.Remove(cat);
                _contenedorTrabajo.Save();
                return Json(new { success = true, message = "Categoria borrada!" });

            }
           

        }


        #endregion


    }
}

Blog/Areas/Admin/Controllers/SlidersController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Blog.AccesoDatos.Data.Repository;
using Blog.Modelos;
using Blog.Modelos.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace Blog.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SlidersController : Controller
    {

        private readonly IContenedorTrabajo _contenedorTrabajo;
        private readonly IWebHostEnvironment _host;


        public SlidersController(IContenedorTrabajo container, IWebHostEnvironment webHost)
        {
            this._contenedorTrabajo = container;
            _host = webHost;
        }
        public IActionResult Index()
        {


            return View();


        }

        public IActionResult Create()
        {
          
            return View();
            


        }
        [HttpPost]
        public IActionResult Create(Slider s)
        {
            
            if (ModelState.IsValid)
            {

                string rutaPrincipal = _host.WebRootPath;
                var archivos = HttpContext.Request.Form.Files;
                if (s.Id == 0)
                {
                    string nombreArchivo = Guid.NewGuid().ToString();
                    var subidas = Path.Combine(rutaPrincipal, @"sliders");
                    var extension = Path.GetExtension(archivos[0].FileName);
                    using (var fileStrean = new FileStream(Path.Combine(subidas, nombreArchivo + extension), FileMode.Create))
                    {
                        archivos[0].CopyTo(fileStrean);
                    }
                    //s.UrlImagen = Path.Combine("sliders" , nombreArchivo , extension);
                    s.UrlImagen = @"\sliders\" + nombreArchivo + extension;

                    s.FechaCreacion = DateTime.Now.ToString();
                    _contenedorTrabajo.UTSlider.Add(s);
                    _contenedorTrabajo.Save();
                    return RedirectToAction(nameof(Index));


                }

            }


            return View(s);
          


        }



        #region AJAXAPI
        [HttpGet]
        public IActionResult GetAll()
        {

            return Json(new { data = this._contenedorTrabajo.UTSlider.GetAll() });

        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            Slider s = this._contenedorTrabajo.UTSlider.Get(id);
            if (s == null)
            {

                return Json(new { success = false, message = "Error borrando el slider" });
            }
            else
            {
                this._contenedorTrabajo.UTSlider.Remove(s);
                _contenedorTrabajo.Save();
                return Json(new { success = true, message = "Slider Borrado!" });

            }


        }



        #endregion

    }
}

Blog/Areas/Admin/Controllers/UsuariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Blog.AccesoDatos.Data.Repository;
using Blog.Modelos.Utilidades;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Blog.Areas.Admin.Controllers
{
    [Authorize(Roles = Constantes.admin)]
    [Area("Admin")]
    public class UsuariosController : Controller
    {

        private readonly IContenedorTrabajo _contenedorTrabajo;


        public UsuariosController(IContenedorTrabajo contenedor)
        {
            _contenedorTrabajo = contenedor;
        }
        public IActionResult Index()
        {
            var claimsIdentity = (ClaimsIdentity)this.User.Identity;
            var usuarioActual = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            return View(_contenedorTrabajo.UTUsuario.GetAll(u => u.Id != usuarioActual.Value));
        }

        [HttpGet]
        public IActionResult Bloquear(string id)
        {
            if(id == null)
            {
                return NotFound();
            }
            else
            {
                _contenedorTrabajo.UTUsuario.bloquearUsuario(id);
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public IActionResult Desbloquear(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            else
            {
                _contenedorTrabajo.UTUsuario.desbloquearUsuario(id);
            }
            return RedirectToAction(nameof(Index));
        }

    }
}

Blog/Views/Shared/_CrearYVolver.cshtml
<div class="row">
    <div class="col">
        <button type="submit" class="btn btn-primary form-control">Crear</button>&nbsp;

    </div>

    <div class="col">
        <a asp-action="Index" class="btn btn-success form-control">Volver a la lista</a>

    </div>


</div>

Blog/Views/Shared/_Layout.cshtml
@using Blog.Modelos.Utilidades;
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Blog</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />



    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>

        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container">
                <a class="navbar-brand" asp-area="Cliente" asp-controller="Home" asp-action="index">Blog</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle text-white" id="menu" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">

                                Contenidos
                            </a>
                            @if(User.IsInRole(Constantes.admin))
                            { 
                            <div class="dropdown-menu" aria-labelledby="menu">
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Categorias" asp-action="Index">Categorias</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Articulos" asp-action="Index">Articulos</a>
                                <a class="dropdown-item" asp-area="Admin" asp-controller="Sliders" asp-action="Index">Sliders</a>

                                <a class="dropdown-item" asp-area="Admin" asp-controller="Usuarios" asp-action="Index">Usuarios</a>



                            </div>
                            }

                        </li>
                    </ul>

                </div>
                <partial name="_LoginPartial" />
            </div>
        </nav>



    </header>
    <div class="container-fluid">
        <main role="main" class="pb-3">
          
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Blog - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://kit.fontawesome.com/6334ab602d.js" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/1.10.20/js/jquery.dataTables.min.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
  
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery.serializeJSON/2.9.0/jquery.serializejson.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>